---
- name: Install required packages
  apt:
    name: "{{ item }}"
  loop:
    - software-properties-common
    - apt-transport-https
- name: Add the PostgreSQL apt key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
- name: Add the PostgreSQL apt repository
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
- name: Install PostgreSQL
  apt:
    name: "postgresql-{{ postgres_version }}"
    update_cache: yes
